const propertiesData = [
  {
    id: 1,
    title: "Modern Glass Villa",
    type: "Villa",
    price: 45000000,
    location: "Bandra West, Mumbai",
    bedrooms: 4,
    bathrooms: 3,
    area: 3200,
    image: "../assets/images/properties/hq_villa_1783545469491.png",
    featured: true,
    badge: "New",
    yearBuilt: "2022",
    furnished: "Fully Furnished",
    amenities: "Pool, Smart Home, Security",
    schools: "1.2 km",
    hospital: "2.5 km",
    rating: "4.9/5",
    agent: "Rahul Sharma",
    agentImage: "../assets/images/agents/agent1.png",
    availability: "Ready to Move",
    parking: "3 Cars",
    status: "Available"
  },
  {
    id: 2,
    title: "Skyline Luxury Apartment",
    type: "Apartment",
    price: 28000000,
    location: "Connaught Place, Delhi",
    bedrooms: 2,
    bathrooms: 2,
    area: 1500,
    image: "../assets/images/properties/hq_apartment_1783545483143.png",
    featured: true,
    badge: "Featured",
    yearBuilt: "2020",
    furnished: "Semi-Furnished",
    amenities: "Gym, Club House, 24/7 Water",
    schools: "0.5 km",
    hospital: "1.0 km",
    rating: "4.7/5",
    agent: "Priya Singh",
    agentImage: "../assets/images/agents/agent2.png",
    availability: "Ready to Move",
    parking: "1 Car",
    status: "Available"
  },
  {
    id: 3,
    title: "Serene Farm House",
    type: "Farm House",
    price: 35000000,
    location: "Lonavala, Maharashtra",
    bedrooms: 5,
    bathrooms: 4,
    area: 5000,
    image: "../assets/images/properties/hq_farmhouse_1783545497287.png",
    featured: true,
    badge: "Sold",
    yearBuilt: "2018",
    furnished: "Fully Furnished",
    amenities: "Private Garden, Pool, Bonfire",
    schools: "5.0 km",
    hospital: "4.2 km",
    rating: "4.8/5",
    agent: "Amit Desai",
    agentImage: "../assets/images/agents/agent3.png",
    availability: "Unavailable",
    parking: "4 Cars",
    status: "Sold"
  },
  {
    id: 4,
    title: "Premium Office Space",
    type: "Office",
    price: 85000000,
    location: "Whitefield, Bangalore",
    bedrooms: 0,
    bathrooms: 4,
    area: 8500,
    image: "../assets/images/properties/hq_commercial_1783545508152.png",
    featured: true,
    badge: "",
    yearBuilt: "2023",
    furnished: "Unfurnished",
    amenities: "Central AC, Cafeteria, High-Speed Elevators",
    schools: "N/A",
    hospital: "1.5 km",
    rating: "4.6/5",
    agent: "Karan Patel",
    agentImage: "../assets/images/agents/agent1.png",
    availability: "Ready to Fit-out",
    parking: "10 Cars",
    status: "Available"
  },
  {
    id: 5,
    title: "Oceanfront Luxury Home",
    type: "Luxury Home",
    price: 95000000,
    location: "Marine Drive, Mumbai",
    bedrooms: 6,
    bathrooms: 7,
    area: 7200,
    image: "../assets/images/properties/oceanfront.png",
    featured: true,
    badge: "New",
    yearBuilt: "2024",
    furnished: "Fully Furnished",
    amenities: "Ocean View, Infinity Pool, Home Theater",
    schools: "2.0 km",
    hospital: "1.8 km",
    rating: "5.0/5",
    agent: "Neha Gupta",
    agentImage: "../assets/images/agents/agent2.png",
    availability: "Under Construction",
    parking: "5 Cars",
    status: "Available"
  },
  {
    id: 6,
    title: "Suburban Family Villa",
    type: "Villa",
    price: 25000000,
    location: "Koregaon Park, Pune",
    bedrooms: 4,
    bathrooms: 3,
    area: 2800,
    image: "../assets/images/properties/suburban.png",
    featured: true,
    badge: "",
    yearBuilt: "2015",
    furnished: "Semi-Furnished",
    amenities: "Park Facing, Kids Play Area",
    schools: "0.8 km",
    hospital: "2.1 km",
    rating: "4.5/5",
    agent: "Vikas Reddy",
    agentImage: "../assets/images/agents/agent3.png",
    availability: "Ready to Move",
    parking: "2 Cars",
    status: "Available"
  },
  {
    id: 7,
    title: "Prime Commercial Complex",
    type: "Commercial",
    price: 150000000,
    location: "Cyber City, Gurgaon",
    bedrooms: 0,
    bathrooms: 8,
    area: 12000,
    image: "../assets/images/properties/commercial.png",
    featured: true,
    badge: "Hot Deal",
    yearBuilt: "2021",
    furnished: "Fully Furnished",
    amenities: "Food Court, Metro Access",
    schools: "N/A",
    hospital: "0.5 km",
    rating: "4.8/5",
    agent: "Sanjay Verma",
    agentImage: "../assets/images/agents/agent1.png",
    availability: "Ready to Move",
    parking: "50+ Cars",
    status: "Available"
  }
];
